### ISSUE TITLE
 Employee Search Page

### ISSUE THREAD

**Issue by razatg** [razatg/reworx#6]
- [x] Fix icon design
- [x] Link the LinkedIn url

**Comment by pradipcoderockers** [comment]
Fix icon design
++ Done
 Link the LinkedIn url
++ Added link url

**Comment by razatg** [comment]
The icon design is still not fixed, please see the location on the recruiter page.
